name = "HubbardAtoms"
uuid = "4f3da25b-ea28-4d4f-a81f-380d3f5e56a6"
version = "0.2.0"
authors = ["Samuel Badr <samuel.badr@tuwien.ac.at>"]

[deps]
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"

[compat]
Aqua = "0.8.18"
LinearAlgebra = "<0.0.1, 1"
ReTestItems = "1.24.0"
SparseIR = "1.0.18,2"
Test = "<0.0.1, 1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "LinearAlgebra", "ReTestItems", "Test"]
